### ISSUE TITLE
IOError during click-spinner 0.1.4 install

### ISSUE THREAD

**Issue by leopoldjuergen** [zhmcclient/python-zhmcclient#120]
### Actual behavior
During pip install zhmcclient we get following error:
```
  Downloading zhmcclient-0.6.0-py2.py3-none-any.whl (70kB)
    100% |████████████████████████████████| 71kB 1.4MB/s 
Collecting click-spinner (from zhmcclient)
  Downloading click-spinner-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rFyCe7/click-spinner/setup.py", line 5, in <module>
        with open('README.md') as f:
    IOError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rFyCe7/click-spinner/
```
### Execution environment

* zhmcclient version: 0.6.0
* Operating system (type+version):

**Comment by andy-maier** [comment]
This is an error in click-spinner that was fixed in click-spinner v0.1.5. Zhmcclient removed the pinning of the click-spinner version in a commit that was merged into zhmcclient v0.8.0.

I suggest to close this issue.
