### ISSUE TITLE
AttributeError: 'Partition' object has no attribute 'cpc'"

### ISSUE THREAD

**Issue by leopoldjuergen** [zhmcclient/python-zhmcclient#161]
### Actual behavior
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ zhmc hba create P000AABB TestPart2 --name PCHID105 --adapter 'FCP 0105 A13B-08' --port 0 --device-number 4711
Traceback (most recent call last):
  File "/usr/local/bin/zhmc", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zhmccli/_cmd_hba.py", line 110, in hba_create
    cmd_ctx.execute_cmd(lambda: cmd_hba_create(cmd_ctx, cpc, partition,
  File "/usr/local/lib/python2.7/dist-packages/zhmccli/_helper.py", line 134, in execute_cmd
    cmd()
  File "/usr/local/lib/python2.7/dist-packages/zhmccli/_cmd_hba.py", line 111, in <lambda>
    options))
  File "/usr/local/lib/python2.7/dist-packages/zhmccli/_cmd_hba.py", line 208, in cmd_hba_create
    adapter = partition.cpc.adapters.find(name=adapter_name)
AttributeError: 'Partition' object has no attribute 'cpc'
```

### Expected behavior
Successful creation of an HBA

### Execution environment

* zhmcclient version: 0.9.0
* Operating system (type+version): Ubuntu 14.04

**Comment by andy-maier** [comment]
PR #162 fixes this.
