### ISSUE TITLE
zhmcclient 0.14.0 fails with pyhton 3.6 installation / TypeError: 'odict_values' object does not support indexing

### ISSUE THREAD

**Issue by tobi1o24** [zhmcclient/python-zhmcclient#372]
### Actual behavior
```
❰tsenner❙~❱✔≻ zhmc -h m12_hmc -u pedebug
Enter 'help' for help, <CTRL-D> or ':q' to exit.
zhmc> cpc list
Enter password (for user pedebug at HMC m12_hmc):
Traceback (most recent call last):
  File "/usr/local/bin/zhmc", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/zhmccli/zhmccli.py", line 241, in cli
    ctx.invoke(repl)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/zhmccli/zhmccli.py", line 285, in repl
    click_repl.repl(ctx, prompt_kwargs=prompt_kwargs)
  File "/usr/local/lib/python3.6/site-packages/click_repl/__init__.py", line 200, in repl
    group.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/zhmccli/_cmd_cpc.py", line 64, in cpc_list
    cmd_ctx.execute_cmd(lambda: cmd_cpc_list(cmd_ctx, options))
  File "/usr/local/lib/python3.6/site-packages/zhmccli/_helper.py", line 173, in execute_cmd
    cmd()
  File "/usr/local/lib/python3.6/site-packages/zhmccli/_cmd_cpc.py", line 64, in <lambda>
    cmd_ctx.execute_cmd(lambda: cmd_cpc_list(cmd_ctx, options))
  File "/usr/local/lib/python3.6/site-packages/zhmccli/_cmd_cpc.py", line 162, in cmd_cpc_list
    print_resources(cpcs, cmd_ctx.output_format, show_list)
  File "/usr/local/lib/python3.6/site-packages/zhmccli/_helper.py", line 269, in print_resources
    print_resources_as_table(resources, output_format, show_list)
  File "/usr/local/lib/python3.6/site-packages/zhmccli/_helper.py", line 360, in print_resources_as_table
    sorted_table = sorted(table, key=lambda row: row[0])
  File "/usr/local/lib/python3.6/site-packages/zhmccli/_helper.py", line 360, in <lambda>
    sorted_table = sorted(table, key=lambda row: row[0])
TypeError: 'odict_values' object does not support indexing
```

### Expected behavior

Should list CPCs.
Works when switching back to python 2.7.13

### Execution environment

Python 3.6.1
zhmc, version 0.14.0

* Operating system (type+version): MacOS 10.12.5
* HMC version: "zNew"
* CPC version: "zNew"

**Comment by andy-maier** [comment]
FIxed in PR #375.
