### ISSUE TITLE
CLI fails on Python 3 due to use of dict.iteritems()

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/python-zhmcclient#396]
### Actual behavior

"zhmc vfunction update" fails with:

```
Traceback (most recent call last):
  File "/usr/local/bin/zhmc", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
 File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/zhmccli/zhmccli.py", line 255, in cli
    ctx.invoke(repl)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/zhmccli/zhmccli.py", line 299, in repl
    click_repl.repl(ctx, prompt_kwargs=prompt_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click_repl/__init__.py", line 200, in repl
    group.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/zhmccli/_cmd_vfunction.py", line 143, in vfunction_update
    cmd_ctx.execute_cmd(lambda: cmd_vfunction_update(cmd_ctx, cpc, partition,
  File "/usr/local/lib/python3.5/dist-packages/zhmccli/_helper.py", line 182, in execute_cmd
    cmd()
  File "/usr/local/lib/python3.5/dist-packages/zhmccli/_cmd_vfunction.py", line 144, in <lambda>
    vfunction, options))
  File "/usr/local/lib/python3.5/dist-packages/zhmccli/_cmd_vfunction.py", line 246, in cmd_vfunction_update
    options = original_options(options)
  File "/usr/local/lib/python3.5/dist-packages/zhmccli/_helper.py", line 213, in original_options
    for name, value in options.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

### Expected behavior

No failure.

This failure is caused by usage of `dict.iteritems()`. Need to replace with `six.iteritems()`

### Execution environment

* zhmcclient version: 0.14.xxx (master)
* Operating system (type+version): Ubuntu 16.04 with Python 3.5
* HMC version: TBD
* CPC version: TBD

**Comment by andy-maier** [comment]
Fixed in PR #397.
