### ISSUE TITLE
CLI: AttributeError calling zhmc vfunction update

### ISSUE THREAD

**Issue by leopoldjuergen** [zhmcclient/python-zhmcclient#416]
### Actual behavior
Attribute error occurred when calling: 

zhmc vfunction update --adapter "zEDC 0188 Z15B-03" CPC1 part1 vfunc

Traceback (most recent call last):
  File "/usr/local/bin/zhmc", line 11, in <module>
    sys.exit(cli())
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zhmccli/zhmccli.py", line 255, in cli
    ctx.invoke(repl)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zhmccli/zhmccli.py", line 299, in repl
    click_repl.repl(ctx, prompt_kwargs=prompt_kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/click_repl/__init__.py", line 200, in repl
    group.invoke(ctx)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zhmccli/_cmd_vfunction.py", line 143, in vfunction_update
    cmd_ctx.execute_cmd(lambda: cmd_vfunction_update(cmd_ctx, cpc, partition,
  File "/usr/local/lib/python2.7/dist-packages/zhmccli/_helper.py", line 182, in execute_cmd
    cmd()
  File "/usr/local/lib/python2.7/dist-packages/zhmccli/_cmd_vfunction.py", line 144, in <lambda>
    vfunction, options))
  File "/usr/local/lib/python2.7/dist-packages/zhmccli/_cmd_vfunction.py", line 252, in cmd_vfunction_update
    adapter = vfunction.partition.manager.cpc.adapters.find(
AttributeError: 'VirtualFunction' object has no attribute 'partition'

### Expected behavior
No error

### Execution environment

* zhmcclient version: 0.16.0
* Operating system (type+version):
* HMC version:
* CPC version:

**Comment by andy-maier** [comment]
Addressed by PR #417.
