### ISSUE TITLE
CLI: Attribute error after aborting delete confirmation

### ISSUE THREAD

**Issue by leopoldjuergen** [zhmcclient/python-zhmcclient#418]
### Actual behavior
If 'N' <enter> or only <enter> is pressed after the 'delete' confirmation, then an attribute error occurs:
 
```zhmc partition delete P000S001 TestPart1
Are you sure you want to delete this partition ? [y/N]: 
Traceback (most recent call last):
  File "/home/vagrant/venv/bin/zhmc", line 10, in <module>
    sys.exit(cli())
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/click/core.py", line 1064, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/click/core.py", line 1404, in handle_parse_result
    self.callback, ctx, self, value)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/click/core.py", line 78, in invoke_param_callback
    return callback(ctx, param, value)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/zhmccli/_helper.py", line 57, in abort_if_false
    raise_click_exception("Aborted.", ctx.error_format)
AttributeError: 'Context' object has no attribute 'error_format'
```

### Expected behavior
Abort without error.

### Execution environment

* zhmcclient version: 0.16.0
* Operating system (type+version):
* HMC version:
* CPC version:

**Comment by andy-maier** [comment]
Fixed in PR #419.
