### ISSUE TITLE
ImportError on build_clib in Travis runs for Python 2.7 and pkg level minimum

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/python-zhmcclient#434]
### Actual behavior

Since a few days ago, the Travis run for Python 2.7 and PACKAGE_LEVEL=minimum fails.

The `make install` step installs the zhmcclient package itself, and that fails:

```
pip install -c minimum-constraints.txt .
Ignoring appnope: markers 'sys_platform == "darwin"' don't match your environment
Processing /home/travis/build/zhmcclient/python-zhmcclient
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/pbr/util.py", line 267, in cfg_to_args
        wrap_commands(kwargs)
      File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/pbr/util.py", line 569, in wrap_commands
        cmdclass = ep.resolve()
      File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2293, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named build_clib
    error in setup command: Error parsing /tmp/pip-tQyBiz-build/setup.cfg: ImportError: No module named build_clib
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-tQyBiz-build/
```

It turns out that Travis uses Ubuntu 14.04 and Python 2.7.13.

The run on Python 2.7 and PACKAGE_LEVEL=latest succeeds.

When using Python 2.7.12 instead (and PACKAGE_LEVEL=minimum), it succeeds.

Looking at the log files (e.g. https://travis-ci.org/zhmcclient/python-zhmcclient/jobs/274588722), it turns out that `pip install setuptools===30.0.0` actually installs 36.0.1:

```
Collecting setuptools===30.0.0 (from -c minimum-constraints.txt (line 21))
  Downloading setuptools-30.0.0-py2.py3-none-any.whl (472kB)
    100% |████████████████████████████████| 481kB 1.7MB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 36.3.0
    Uninstalling setuptools-36.3.0:
      Successfully uninstalled setuptools-36.3.0
Successfully installed setuptools-36.0.1
```

When installing `pip install setuptools===36.0.1` directly, it succeeds.

### Expected behavior

It should install setuptools 30.0.0 and should succeed, as before.

### Execution environment

* zhmcclient version: 2.16.1.devXX
* Operating system (type+version): Ubuntu 14.04 (Travis CI runs)
* HMC version: N/A
* CPC version: N/A

**Comment by andy-maier** [comment]
I have opened issue pypa/pip#4724 to get some help from the Pip project.

**Comment by andy-maier** [comment]
It turns out that installing setuptools===30.0.0 a second time results in 30.0.0 actually being installed and causes the ImportError not to show up. This seems to be a working circumvention of the issue.

**Comment by andy-maier** [comment]
It turns out that the build_clib issue is directly linked to the fact that on the trusty distro in Travis, the setuptools package had two metadata directories. PR #450 provides a better fix for the issue, by deleting the outdated metadata directory.

**Comment by andy-maier** [comment]
One suggestion of the Pip team was not to use `===` in the minimum constraints file, but to use `==` instead.

Using `===` is documented as "arbitrary equality" in PEP 440. Its documented purpose is to make sure  `1.0' is used when versions such as '1.0+localidentifier` are around. See https://www.python.org/dev/peps/pep-0440/#local-version-identifiers.

There is some uncertainty as to whether `===` is really doing just a string comparison of the versions strings (so that `0030===30` would not match), versus still would be doing some amount of normalization.

**Comment by andy-maier** [comment]
PR #485 changes the use of `===` in the minimum coinstraints file to `==`.
