### ISSUE TITLE
Fix TypeError when calling __init__() of MetricGroupDefinition

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/python-zhmcclient#478]
### Actual behavior

Using the metrics support in the zhmcclient module results in the following TypeError on Python 3:

```
Traceback (most recent call last):
  File "examples/metrics.py", line 87, in <module>
    'metric-groups': metric_groups})
  File "<decorator-gen-124>", line 2, in create
  File "/home/maiera/virtualenvs/zhmc36/lib/python3.6/site-packages/zhmcclient/_logging.py", line 202, in log_api_call
    result = func(*args, **kwargs)
  File "/home/maiera/virtualenvs/zhmc36/lib/python3.6/site-packages/zhmcclient/_metrics.py", line 190, in create
    mc_properties)
  File "/home/maiera/virtualenvs/zhmc36/lib/python3.6/site-packages/zhmcclient/_metrics.py", line 230, in __init__
    self._metric_group_definitions = self._setup_metric_group_definitions()
  File "/home/maiera/virtualenvs/zhmc36/lib/python3.6/site-packages/zhmcclient/_metrics.py", line 244, in _setup_metric_group_definitions
    metric_definitions=dict())
  File "/home/maiera/virtualenvs/zhmc36/lib/python3.6/site-packages/zhmcclient/_metrics.py", line 346, in __init__
    name, resource_class, metric_definitions)
TypeError: object.__init__() takes no parameters
```

### Expected behavior

Should work.

### Execution environment

* zhmcclient version: master
* Operating system (type+version): RHEL 7.4
* HMC version: N/A
* CPC version: N/A

**Comment by andy-maier** [comment]
This seems to be caused by using `__init__()` in the metrics classed that are derived from namedtuple. See https://stackoverflow.com/q/48853916/1424462.

**Comment by andy-maier** [comment]
The coding error is fixed in PR #482.
Adding test cases will be left for a separate PR (see issue #476).
