### ISSUE TITLE
 AttributeError when calling partition.list_attached_storage_groups()

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/python-zhmcclient#629]
Submitted by Björn Walk:

### Actual behavior
```
$ cat script.py
#!/usr/bin/env python3

import sys
import zhmcclient
import requests.packages.urllib3
requests.packages.urllib3.disable_warnings()

HMC_HOST = "localhost"
HMC_USER = "sysprog"
HMC_PASS = "********"

partition_name = "m46lp74"

if __name__ == '__main__':
    print(zhmcclient._version.__version__)

    session = zhmcclient.Session(HMC_HOST, HMC_USER, HMC_PASS)
    client = zhmcclient.Client(session)
    cpc = client.cpcs.find(name="M46")

    partition = cpc.partitions.find(name=partition_name)

    print(partition.list_attached_storage_groups())
```
```
$ ./script.py
0.23.0
Traceback (most recent call last):
  File "./script.py", line 24, in <module>
    print(partition.list_attached_storage_groups())
  File "</home/bwalk/.venv/zhmc/lib/python3.7/site-packages/decorator.py:decorator-gen-69>", line 2, in list_attached_storage_groups
  File "/home/bwalk/.venv/zhmc/lib/python3.7/site-packages/zhmcclient/_logging.py", line 223, in log_api_call
    result = func(*args, **kwargs)
  File "/home/bwalk/.venv/zhmc/lib/python3.7/site-packages/zhmcclient/_partition.py", line 1207, in list_attached_storage_groups
    sg = cpc.storage_groups.resource_object(sg_uri)
AttributeError: 'Cpc' object has no attribute 'storage_groups'


### Expected behavior


### Execution environment

* zhmcclient version: 0.23.0
* Operating system (type+version): Linux Fedora 29
* HMC version: 2.14.1
* CPC version:
Version: 2.14.1

**Comment by andy-maier** [comment]
Fixed in PR #634 for master and #632 for 0.26.1.
