### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [zhmcclient/python-zhmcclient#651]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.26.1. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary zhmcclient -w /tmp/ext zhmcclient==0.26.1
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting zhmcclient==0.26.1
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/3c9/d8eee4cd460fe/zhmcclient-0.26.1.tar.gz (153 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-gxgxyj6o/zhmcclient/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-gxgxyj6o/zhmcclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-gxgxyj6o/zhmcclient/pip-egg-info
         cwd: /tmp/pip-wheel-gxgxyj6o/zhmcclient/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-gxgxyj6o/zhmcclient/setup.py", line 67, in <module>
        requirements = get_requirements('requirements.txt')
      File "/tmp/pip-wheel-gxgxyj6o/zhmcclient/setup.py", line 47, in get_requirements
        with open(requirements_file, 'r') as fp:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by andy-maier** [comment]
Hi Tim. I like your computer naming scheme :-)

Sorry for not reacting to this issue any earlier :-(

We'll add the file and will also add an install test from various sources. Unfortunately we cannot accept your PR because its commit is not signed and thus does not satisfy the contribution guidelines. Also, the docs need an update to better explain from which sources it can be installed, and the install test needs to be added. You don't need to worry about that, I'll pick that from another project that already does that.
