### ISSUE TITLE
How to handle JMS errors

### ISSUE THREAD

**Issue by kriolyth** [zhmcclient/python-zhmcclient#770]
**Describe the bug**
On a rare occasion an attempt to read Operating System Messages stream fails with an error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/stomp/transport.py", line 341, in __receiver_loop
    self.process_frame(f, frame)
  File "/usr/local/lib/python3.6/dist-packages/stomp/transport.py", line 187, in process_frame
    self.notify(frame_type, f.headers, f.body)
  File "/usr/local/lib/python3.6/dist-packages/stomp/transport.py", line 241, in notify
    rtn = notify_func(headers, body)
  File "/usr/local/lib/python3.6/dist-packages/zhmcclient/_notification.py", line 319, in on_error
    (headers, message))
RuntimeError: Unexpectedly received a JMS error (JMS headers: {'content-type': 'text/plain', 'message': "  remote addConsumer failed because the specified destination, 'topic://TESSIA.17343osm.3a9e0fc274e511eab0cb00106f0d9fd1', is not a known or approved topic."}, JMS message: "java.lang.SecurityException:   remote addConsumer failed because the specified destination, 'topic://TESSIA.17343osm.3a9e0fc274e511eab0cb00106f0d9fd1', is not a known or approved topic.\n\tat
...
<long traceback follows>
```

This traces back to `on_error` handler in NotificationListener:
```
    @staticmethod
    def on_error(headers, message):
        """
        This event method should never be called, because the HMC does not
        issue JMS errors.
        For parameters, see
        :meth:`~zhmcclient.NotificationListener.on_message`.
        """
        raise RuntimeError("Unexpectedly received a JMS error "
                           "(JMS headers: %r, JMS message: %r)" %
                           (headers, message))
```

Unfortunately, raise occurs in some other thread (stomp listener?), and effectively the NotificationListener is unusable after that.

**To Reproduce**
This is a very rare event in our scenarios, but listening to a wrong topic on purpose raises this error:
```
# Fill in as needed
# hmc_host = 
# hmc_userid = 
# hmc_password = 
# cpc_name = 
# partition_name = 

session = zhmcclient.Session(hmc_host, hmc_userid, hmc_password)
client = zhmcclient.Client(session)
cpc = client.cpcs.find(name=cpc_name)
lpar = cpc.lpars.find(name=partition_name)

topic = lpar.open_os_message_channel(include_refresh_messages=True) + 'f'  # corrupt topic

receiver = zhmcclient.NotificationReceiver(
    topic, hmc_host, hmc_userid, hmc_password)
for headers, message in receiver.notifications():
    print(headers, message)

```

**Expected behavior**
Rather than expecting some behaviour, my question is: how to better handle this exception?

**Environment information**
* Output of `python -m zhmcclient.debuginfo`:
Operating system: Linux 4.15.0-140-generic on s390x
Python implementation: CPython 3.6.9 (64 bit, wide unicode)
Python version: 3.6.9
zhmcclient version: 0.30.1

* HMC version: 2.15.0
* HMC API version: 3.8

**Comment by andy-maier** [comment]
I agree that the handling of this situation should recover better than it does now.

**Comment by andy-maier** [comment]
@kriolyth Hi Alex. I was able to reproduce the error on a z14 in classic mode, thanks to your great reproduction code. I have created PR #771 that addresses the issue. Note that there are two new exceptions that can now be raised from within `Notificationreceiver.notifications()`. See the commit message for details.

Please review the solution, and try it out and let me know whether it works for you.

Here is a version of your reproduction code that shows how to use the new exceptions:

```
#!/usr/bin/env python

import sys
import zhmcclient
import requests

requests.packages.urllib3.disable_warnings()

# Fill in as needed
# hmc_host = 
# hmc_userid = 
# hmc_password = 
# cpc_name = 
# lpar_name = 

session = zhmcclient.Session(hmc_host, hmc_userid, hmc_password)
client = zhmcclient.Client(session)
cpc = client.cpcs.find(name=cpc_name)
lpar = cpc.lpars.find(name=lpar_name)

topic = lpar.open_os_message_channel(include_refresh_messages=True) + 'f'  # corrupt topic

receiver = zhmcclient.NotificationReceiver(topic, hmc_host, hmc_userid, hmc_password)

try:
    for headers, message in receiver.notifications():
        print("Info: Got a notification: headers={}, message={}".format(headers, message))
except zhmcclient.NotificationError as exc:
    print("Error: {}: {}".format(exc.__class__.__name__, exc))
    print("       JMS headers: {!r}".format(exc.jms_headers))
    print("       JMS message: {!r}".format(exc.jms_message))
```

**Comment by kriolyth** [comment]
Hi Andreas, from my perspective it works great, thank you for resolving this issue!

**Comment by andy-maier** [comment]
Ok, then I will merge it and release a fix version.
