### ISSUE TITLE
pywinpty fails installing on py27/windows/latest

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/python-zhmcclient#772]
Somewhere between 2021-04-25 and Since 2021-05-02, `make develop` started failing on Python 2.7 on Windows with latest package levels, when installing the "pywinpty" package.

From https://github.com/zhmcclient/python-zhmcclient/runs/2593244433?check_suite_focus=true:
```
Collecting pywinpty>=0.5; os_name == "nt"
  Downloading pywinpty-1.0.1.tar.gz (47 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'C:\hostedtoolcache\windows\Python\2.7.18\x64\python.exe' 'C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'c:\users\runner~1\appdata\local\temp\tmpsf_reo'
       cwd: c:\users\runner~1\appdata\local\temp\pip-install-hjjgyi\pywinpty
  Complete output (15 lines):
  Traceback (most recent call last):
    File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 108, in get_requires_for_build_wheel
      backend = _build_backend()
    File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 86, in _build_backend
      obj = import_module(mod_path)
    File "C:\hostedtoolcache\windows\Python\2.7.18\x64\lib\importlib\__init__.py", line 37, in import_module
      __import__(name)
    File "c:\users\runner~1\appdata\local\temp\pip-build-env-3budfg\overlay\Lib\site-packages\maturin\__init__.py", line 31
      def get_config() -> Dict[str, str]:
                       ^
  SyntaxError: invalid syntax
```

**Comment by andy-maier** [comment]
It turns out that pywinpty does not have metadata about the required Python versions and dependent packages on Pypi. That causes pip to pick the latest released version which requires the "maturin" package which uses the new type syntax added in Python 3.6.

I opened issue https://github.com/spyder-ide/pywinpty/issues/153 for the missing metadata

Not yet understood is why it fails only on py27, but not on py35. In both cases, pip 20.3.4 was used.
The "maturin" package was started to be used by pywinpty in its version 1.0.0. The maturin properly declares its minimum python version on Pypi (3.5 or 3.6), but because it is not recognized as a dependent by pip due to the missing metadata in pywinpty, pip does realize that pywinpty 1.0.0 or later will fail below the minimum python version required by maturin.

Circumvention is to pin pywinpty<1.0.0 on python<3.6.
