### ISSUE TITLE
cpcinfo -a raises TypeError

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/python-zhmcclient#86]
Recording this issue on behalf of Elisabeth:

Using cpcinfo -a raises the following exception:

```
Traceback (most recent call last):
  File "/usr/local/bin/cpcinfo", line 304, in <module>
    main()
  File "/usr/local/bin/cpcinfo", line 225, in main
    key=lambda p: p.prop('card-location')):
TypeError: unorderable types: NoneType() < str()
```

Investigation shows that this only shows up on Python 3, but not on Python 2.7. So far, cpcinfo had only been tested oin Python 2.7.

**Comment by andy-maier** [comment]
Fixed in PR #87.

Reason was that Python 3 is more strict in keys used in `sorted()`: A value of `None` is tolerated in Python 2, but raises `TypeError` in Python 3. Fixed by defaulting the property values used as keys to the empty string, instead of defaulting them to `None`.
