### ISSUE TITLE
make installtest fails on Python 2.7 with minimum package levels

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/python-zhmcclient#915]
From PR #914 against zhmcclient 1.1.1:

Log: https://github.com/zhmcclient/python-zhmcclient/runs/5230093607?check_suite_focus=true

```
Makefile: Running install tests
tests/installtest/test_install.sh dist/zhmcclient-1.1.1-py2.py3-none-any.whl dist/zhmcclient-1.1.1.tar.gz python
Preparing for the tests
Creating test directory: /Users/runner/work/python-zhmcclient/python-zhmcclient/tmp_installtest
Creating source archive unpack directory: /Users/runner/work/python-zhmcclient/python-zhmcclient/tmp_installtest/src_dist
Removing .egg file: /Users/runner/work/python-zhmcclient/python-zhmcclient/dist/zhmcclient*.egg
Testcase test1: Pip install from repo root directory: /Users/runner/work/python-zhmcclient/python-zhmcclient
Before creating virtualenv: /Users/runner/work/python-zhmcclient/python-zhmcclient/tmp_installtest/virtualenvs/zhmcclient_test_test1
Python version: Python 2.7.18 from /Users/runner/hostedtoolcache/Python/2.7.18/x64/bin/python
Pip version: pip 9.0.1 from /Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages (python 2.7)
Creating virtualenv using virtualenv: /Users/runner/work/python-zhmcclient/python-zhmcclient/tmp_installtest/virtualenvs/zhmcclient_test_test1
Error: Command failed with rc=1: virtualenv -p /Users/runner/hostedtoolcache/Python/2.7.18/x64/bin/python  /Users/runner/work/python-zhmcclient/python-zhmcclient/tmp_installtest/virtualenvs/zhmcclient_test_test1, output follows:
Already using interpreter /Users/runner/hostedtoolcache/Python/2.7.18/x64/bin/python
New python executable in /Users/runner/work/python-zhmcclient/python-zhmcclient/tmp_installtest/virtualenvs/zhmcclient_test_test1/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /Users/runner/work/p...est_test1/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/virtualenv_support/pip-8.0.0-py2.py3-none-any.whl/pip/__init__.py", line 15, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/virtualenv_support/pip-8.0.0-py2.py3-none-any.whl/pip/vcs/subversion.py", line 9, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/virtualenv_support/pip-8.0.0-py2.py3-none-any.whl/pip/index.py", line 29, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/virtualenv_support/pip-8.0.0-py2.py3-none-any.whl/pip/wheel.py", line 32, in <module>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/virtualenv_support/pip-8.0.0-py2.py3-none-any.whl/pip/pep425tags.py", line 214, in <module>
make: *** [installtest] Error 1
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/virtualenv_support/pip-8.0.0-py2.py3-none-any.whl/pip/pep425tags.py", line 162, in get_supported
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/virtualenv_support/pip-8.0.0-py2.py3-none-any.whl/pip/pep425tags.py", line 119, in get_platform
ValueError: need more than 2 values to unpack
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/virtualenv.py", line 702, in main
    symlink=options.symlink)
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/virtualenv.py", line 903, in create_environment
    download=download,
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/virtualenv.py", line 860, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/virtualenv.py", line 780, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/runner/work/p...est_test1/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1
Error: Process completed with exit code 2.
```

**Comment by andy-maier** [comment]
By experimenting, found that using virtualenv 14.0.6 solves the problem.
