### ISSUE TITLE
KeyError: 'status' when running example5.py

### ISSUE THREAD

**Issue by leopoldjuergen** [zhmcclient/python-zhmcclient#99]
When running example5.py I get following error:

Stopping Partition TestPart1 ...
Traceback (most recent call last):
  File "./example5.py", line 116, in <module>
    partition.stop()
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/zhmcclient/_partition.py", line 323, in stop
    wait_for_completion=wait_for_completion)
  File "<decorator-gen-5>", line 2, in post
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/zhmcclient/_logging.py", line 132, in wrapper
    result = func(*args, **kwargs)
  File "/home/vagrant/venv/local/lib/python2.7/site-packages/zhmcclient/_session.py", line 475, in post
    if result_object['status'] == 'complete':
KeyError: 'status'

**Comment by andy-maier** [comment]
Fixed in PR #100.
